### ISSUE TITLE
Direktlänk som ger bokningsbehörighet

### ISSUE THREAD

**Issue by carlcrafoord** [d-tamm/ff-boka#143]
Skapa länk till en bokningsresurs tex kajakerna som bara är tillgänglig för de med länken. Då kan vi prelboka ett gäng kajaker inför en helg och låta de med länken få boka prelbokade kanoter. Övriga ser att det är x antal kanoter som är prelbokade och kan boka ev överskjutande del

**Comment by carlcrafoord** [comment]
Lite pysslig textruta för att lägga in ärendet eller det kanske ska vara en rubrik med text under

**Comment by d-tamm** [comment]
Tack Carl! Ja, det år så som du misstänkte att textrutan är tänkt för en kort rubrik, och den större rutan för att förklara mer ingående. Jag har justerat nu så det blir en hanterbar rubrik. :)

**Comment by d-tamm** [comment]
Lite funderingar kring själva förfrågan: Ett sätt att hantera detta utan att behöva lägga till någon funktionalitet i bokningssystemet är att skapa äventyret med 2 grupper - en grupp för folk som har egen kanot, och en grupp för de som inte har. Man kan även sätta en maxstorlek på den andra gruppen, t.ex. 10 personer. Och så bokar aktivitetsledaren 10 st kanoter i resursbokningen. Deltagarna behöver då alltså inte själva hantera några bokningar av materiel, utan bokar bara in sig på rätt grupp.
Jag ser just nu inte vad en direktlänk som ger bokningsbehörighet skulle tillföra jämfört med upplägget som jag beskriver. Detta även med tanke på bokningsflödet som det är nu (att alla resurser i LA visas samlat på en sida), där det inte går att visa en viss kategori eller resurs. En direktlänk till t.ex. en kategori skulle alltså kräva en helt ny vy, samt hanteringen av tokens för behörigheten. Båda går att ordna, men det bör tillföra något för att man ska lägga energi på det.

**Comment by d-tamm** [comment]
Överlappar med #14. Fortsätt vidare diskussion där.
