### ISSUE TITLE
Underkategori - behörighet

### ISSUE THREAD

**Issue by carlcrafoord** [d-tamm/ff-boka#148]
![image](https://user-images.githubusercontent.com/61828859/76164611-9b5c0b00-6150-11ea-807b-6246b8ecb697.png)

**Comment by d-tamm** [comment]
Jag ser att du har lyckats lägga in underkategorin Beachflaggor. Har ditt problem löst sig? Beskriv annars gärna vad som exakt är problemet.

**Comment by carlcrafoord** [comment]
Jag behöver göra en överkategori innan jag kan skapa en under
så du kan släcka den här, man det behövs info i hjälptext

**Comment by d-tamm** [comment]
Det går även att i efterhand skapa en överordnad kategori och sedan flytta underkategorin så den hamnar på önskat ställe i hierarkin.
@carlcrafoord Om du tycker att hjälptexten behöver kompletteras och själv nu har förstått hur man ska göra, skriv gärna ett förslag på nya texten i hjälpen.
