### ISSUE TITLE
Bokningsfråga  - admin kan lägga upp och jag är admin

### ISSUE THREAD

**Issue by carlcrafoord** [d-tamm/ff-boka#149]
![image](https://user-images.githubusercontent.com/61828859/76164652-df4f1000-6150-11ea-9aed-6b6795b43513.png)

**Comment by d-tamm** [comment]
Bokningsfrågor läggs upp på LA-nivå, inte på kategorinivå. I kategorin kan du sedan välja frågor som har lagts upp på LA-nivå.

**Comment by d-tamm** [comment]
Har nu lagt till lite text så det ska vara tydligare.
