### ISSUE TITLE
Sök prylar oavsett lokalavdelning

### ISSUE THREAD

**Issue by carlcrafoord** [d-tamm/ff-boka#153]
Exempel: en lokalavdelning behöver fler kanoter till en tur
För att slippa kolla på om de lokalavdelningarna i närheten har kanoter så skulle det vara bra att kunna söka på "vilka har kanoter" som komplement till att söka på lokalavdelningar.

Ta till exempel mora som har 6 bra kanoter då kan jag hyra dom på plats i Mora om jag vill paddla där istället för att ta med från någon lokalavdelning när. Eller tex mölndal....

**Comment by d-tamm** [comment]
Det bör kombineras med en geografisk avgränsning eller sortering. Det går att hämta lat/lon från https://nominatim.openstreetmap.org/search?format=json&limit=1&q=Dals Eds kommun
Sökningen på lat/lon bör bara göras när LA-listan uppdateras, och resultaten sparas i databasen.

**Comment by d-tamm** [comment]
Via HTML5 geolocation API (javascript) går det att ta reda om användarens position (efter samtycke).
https://www.codexworld.com/get-visitor-location-using-html5-geolocation-api-php/
