### ISSUE TITLE
Går inte att nå boka.friluftsframjandet.se från tel och pc på riks

### ISSUE THREAD

**Issue by carlcrafoord** [d-tamm/ff-boka#154]
Jag har kollat runt och en iphone funkade mot boka.friluftsframjandet.se, den hade inte uppdaterats och var inte uppkopplad mot vårt wifi.
 
Övriga telefoner kunde inte koppla upp sig mot boka....

Jag tror att det har att göra med uppsättningen hos vår brandvägg men det kan ju vara ett mer generellt problem

**Comment by d-tamm** [comment]
I och med att domänen går att nå från andra ställen (jobbet hos mig, hemma hos mig, mobilen, tåget) så är detta inget problem som har med resursbokningen att göra. Jag lämnar dock posten än så länge öppen för ev felsökning.
Är alla prylar som inte kan nå boka.ff.se upplopplade via samma Wlan-nätverk?

**Comment by d-tamm** [comment]
@carlcrafoord  är det OK att stänga den här?
