### ISSUE TITLE
Missing admin functionality

### ISSUE THREAD

**Issue by gabrieltiste** [d-tamm/ff-boka#362]
**Describe the bug**
Missing admin functionality. I have tried to login with my account and I cannot find the admin functionality. Our ordförande cannot see it either.

**To Reproduce**
1. Login
2. No admin functions, booking appears but that is it.

**Expected behavior**
I expect that after login, I can see a button or something that will take me to the administration part of ff-boka.

**Screenshots**
<img width="687" alt="Skärmavbild 2022-11-22 kl  20 26 51" src="https://user-images.githubusercontent.com/9597983/203404018-d909743a-ab76-46e8-847d-77a5c88500fd.png">

**Desktop (please complete the following information):**
 - OS: Mac OS x
 - Browser safari

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, safari, firefox]

**Additional context**

**Comment by d-tamm** [comment]
I am looking at this. Something is crashing during the generation of the landing page so the lower part of the page (including the admin links) is not generated.
Meanwhile, you can still get to the admin page with this address:
boka.friluftsframjandet.se/admin/?sectionId=`ID`
where `ID` is the ID of your lokalavdelning. To get that, look at the link of the button "Boka resurser i ..." which ends with ?sectionId=`ID`

**Comment by d-tamm** [comment]
Was probably related to new PHP version and datetime functions which have been reviewed since then. Closing.
